GOVINDDIXIT/IIITL-Student-APP

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/menu/drawer_menu.xml, app/src/main/res/values/strings.xml
=> Add getsetfoss site to the navigation drawer

Technical Staff.json
=> create a json for Axios team

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/menu/drawer_menu.xml
=> remove items from navigation drawer

Blogs/article.md
=> Add Article on Android Gesture

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/menu/drawer_menu.xml, app/src/main/res/values/strings.xml
=> Add DSC Site

Blogs/article.md
=> Write a technical article on any topic in android development #31

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/menu/drawer_menu.xml, app/src/main/res/values/strings.xml
=> (Fix #50 ) Added equinox website 

app/src/main/AndroidManifest.xml, app/src/main/java/govind/iiitl/app/AskDetail.java, app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/layout/activity_ask_detail.xml, app/src/main/res/values/strings.xml
=> fix: Make Ask Details

app/src/main/java/govind/iiitl/app/AboutPage.java, app/src/main/res/layout/activity_about_page.xml
Replace Webview to CromeCustomTab in the About Us.
Improve UI of About US
=> fix: Improve About Us

app/src/main/java/govind/iiitl/app/AboutPage.java, app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/java/govind/iiitl/app/SignIn/LogOut.java, app/src/main/res/layout/activity_log_out.xml, app/src/main/res/layout/header.xml, app/src/main/res/layout/post_item.xml
fix the UI of Logout Activity.
change web view to cromecustomtab.
fix header image and text overlapping
=> fix: logout screen improve and refactor

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/assets/faculty.json, app/src/main/java/govind/iiitl/app/Adapter/FacultyAdapter.java, app/src/main/java/govind/iiitl/app/FacultyActivity.java, app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/java/govind/iiitl/app/Models/Faculty.java, app/src/main/res/layout/activity_faculty.xml, app/src/main/res/layout/faculty_item.xml, app/src/main/res/menu/drawer_menu.xml
=> feat: Faculty section

app/build.gradle, app/src/main/res/layout/faculty_item.xml
=> fix: Add Circle background

app/src/main/assets/timetable/cs2sem.json, app/src/main/assets/timetable/it1sem.json, app/src/main/assets/timetable/it2sem.json, app/src/main/assets/timetable/it3sem.json, app/src/main/assets/timetable/it4sem.json, app/src/main/assets/timetable/it5sem.json, app/src/main/assets/timetable/it6sem.json, app/src/main/assets/timetable/it7sem.json, app/src/main/assets/timetable/it8sem.json, app/src/main/assets/timetable/mcs1sem.json, app/src/main/assets/timetable/mcs2sem.json, app/src/main/java/govind/iiitl/app/AskDetail.java, app/src/main/java/govind/iiitl/app/FacultyActivity.java, app/src/main/java/govind/iiitl/app/Fragments/Fri.java, app/src/main/java/govind/iiitl/app/Fragments/Mon.java, app/src/main/java/govind/iiitl/app/Fragments/Thu.java, app/src/main/java/govind/iiitl/app/Fragments/Tue.java, app/src/main/java/govind/iiitl/app/Fragments/Wed.java, app/src/main/java/govind/iiitl/app/TimeTable.java, app/src/main/res/layout/activity_ask_detail.xml, app/src/main/res/layout/fragment_fri.xml, app/src/main/res/layout/fragment_mon.xml, app/src/main/res/layout/fragment_thu.xml, app/src/main/res/layout/fragment_tue.xml, app/src/main/res/layout/fragment_wed.xml, app/src/main/res/values/strings.xml
fix #66 
Added Mtech raw JSON file.
Complete Time Table viewer for all trades and their respective semesters.
=> feat: Inflate timetable json

app/src/main/java/govind/iiitl/app/SignIn/LogOut.java
=> fix: Add Alert box in while logging out

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/res/layout/activity_main.xml
=> feat: Add swipe refresh for Main feed

app/src/main/assets/faculty.json
=> Removed AP & DR sir from Faculty list

app/src/main/assets/faculty.json
=> Added Photo of AM Sir

app/src/main/res/values/strings.xml
=> fix: broken E-cell link

app/src/main/java/govind/iiitl/app/activities/VerifyActivity.kt, app/src/main/res/layout/activity_verify.xml
Closes issue #126 
Added the mentioned functionality and checked that it is working properly @GOVINDDIXIT you can review it
=> Minor changes related to VerifyActivity

app/src/main/java/govind/iiitl/app/MainActivity.java
=> Navigation drawer closes on opening any other activity

app/src/main/java/govind/iiitl/app/MainActivity.java, app/src/main/java/govind/iiitl/app/activities/ArchiveActivity.java, app/src/main/res/layout/activity_archive.xml
Added the functionality and checked it by running with disabling the default handler in the onCreate and refreshing it
This closes #129 
@refactor-droidyy tell me if some more modifications are needed in this
=> Swipe Refresh functionality added in Archive Activity

app/src/main/java/govind/iiitl/app/activities/TimeTableActivity.java
=> tab-transition-bug-fixed

app/src/main/java/govind/iiitl/app/activities/TimeTableActivity.java
This closes #135 
@refactor-droidyy this is the change I initially intended to make but I have one more idea, using the TextViews of tabs of different days within an array so that they can be accessed by index which would make the code very much shorter and simpler using loops. Would doing this be considered as obfuscation of the code ?
=> code redundancy reduced

app/src/main/java/govind/iiitl/app/activities/TimeTableActivity.java, app/src/main/res/drawable/fragment_bg.xml, app/src/main/res/layout/activity_time_table.xml, app/src/main/res/layout/fragment_fri.xml, app/src/main/res/layout/fragment_mon.xml, app/src/main/res/layout/fragment_thu.xml, app/src/main/res/layout/fragment_tue.xml, app/src/main/res/layout/fragment_wed.xml, app/src/main/res/layout/tab_bar.xml, app/src/main/res/layout/timetable.xml
=> timetable ui modified

app/src/main/assets/faculty.json, app/src/main/res/layout/faculty_item.xml
Updated Faculty Section :-
1. Added info of new faculty members
2. Added and updated the image links
Closes #167
=> udpated-faculty-section
